### ISSUE TITLE
Remove redundant toString() method for units.

### ISSUE THREAD

**Issue by TAKBS2412** [robototes/2412RobotLibrary#1]
Currently this method is implemented in the exact same way for each unit:

````java
public String toString() {
	return StringUtils.getFormattedValue(getValue(), 4) + this.getUnit();
}
````

It would be better to avoid this redundancy somehow. One possibility would be adding a default implementation to the `IUnit` interface (this is a new Java 8 feature).

**Comment by OroArmor** [comment]
Java 8 does not allow interfaces to override java.lang.object methods, and switching one unit would mess a lot of code up.
